name = "FAN Min"
# avatar = "images/profile.png" # Avatar image. Default to "images/profile.webp".
bio = "Researcher, Public Health, Pharmocoloepidemiology"
company = "HKU"
location = "HK, China, Earth"
