baseURL: https://example.com
title: Blog - FAN Min
theme: hugo-theme-bootstrap
copyright: Copyright © 2016-{year} Razon Yang. All Rights Reserved.
defaultContentLanguage: en
defaultContentLanguageInSubdir: yes
paginate: 5
enableRobotsTXT: yes
enableEmoji: yes
blackfriday:
  hrefTargetBlank: yes
outputs:
  home:
    - HTML
    - RSS
    - JSON
taxonomies:
  category: categories
  series: series
  tag: tags
